### ISSUE TITLE
NODE - Changes to Activity and Activity Details

### ISSUE THREAD

**Issue by sbenemerito** [hugh-n/JF-Learning#127]
With reference to #124 , changes will be made to Activity and Activity Details

### Table changes:
- [x] **Activity** table's `unit_id` now `question_id` (FK to Questions table)
- [x] **Activity** table's `activity_type` will now be removed (Will now be based on Question instance's `learn_type` field)
- [x] **ActivityDetail** table's `question_id` now `content_id` (FK to Contents table)

### API changes:
- [x] Content (actual question and answer) will now be taken from **Contents** table, based on listed **content_ids** in **Question** instance

**Comment by markusviola** [comment]
@sbenemerito tasks finished.
