### ISSUE TITLE
NODE - Homework API

### ISSUE THREAD

**Issue by hugh-n** [hugh-n/JF-Learning#32]
Create the following API for frontend:

GET
/lessons - Get all lessons
/lessons/:lesson_id - Get only one lesson data
/lessons/:lesson_id/terms - Get all terms of lesson
/lessons/:lesson_id/terms/:term_id - Get one specific term
/lessons/:lesson_id/test - Get test items

POST
lesson/log/study - Generate log when user starts studying
lesson/log/test - Generate user score and log when user finishes test

**Comment by hugh-n** [comment]
- [/lessons, /lessons/:lesson_id ]

**Comment by hugh-n** [comment]
Second list of API's to create.

GET
- [ ] /lessons/:lesson_id/test - Send list of test questions

POST
- [ ] lesson/log/study - Generate log when user starts studying
- [ ] lesson/log/test - Generate log, incomplete student test_result and, test_result_details

PATCH
- [ ] lesson/log/study - Update log with finish_time
- [ ] lesson/log/test - Update log with finish_time, test_result with score, and test_result_details with answers

**Comment by hugh-n** [comment]
Additional API's to create.

GET

- [ ] /lessons/student/:id - Get all lessons of student
- [ ] /lessons/sets - Get all lesson sets
- [ ] /lessons/sets/:id - Get specific lesson set
- [ ] /lessons/sets/student/:id - Get lesson sets of specified student

**Comment by sbenemerito** [comment]
Changed issue name from `Lesson API` to `Homework API`. Don't forget to change everything to `homework` too :+1:
